# # Site
# favicon: images/favicon.ico

# # Personal info
# name: Tim-Oliver Buchholz
# title: Machine Learning Expert for Image Analysis
# email: contact-tibuch@protonmail.ch
# #website: https://tibuch.ch

# # Dark Mode (true/false/never)
# darkmode: false

# # Social links
# github_username:  tibuch
# linkedin_username: tibuch
# orcid_username: 0000-0001-6953-8915

# # Additional icon links
# additional_links:
# - title: Current Workplace
#   icon: fas fa-globe
#   url: https://www.fmi.ch/platforms/platform.html?plt=110

# # About Section
# # about_title: About Me
# about_profile_image: images/profile.jpg
# about_content: | # this will include new lines to allow paragraphs
#   Hi, my name is Tim-Oliver and I am a research software engineer. I work on biomedical image processing and analysis 
#   pipelines. Next to my work as software engineer I educate researchers in the best practices of FAIR image processing 
#   and analysis. I have worked with a number of different research groups and have experience in a wide range of image 
#   processing and analysis tasks.
  
#   In my day-to-day work I use a variety of different programming languages and tools. I am experienced in Python and Java,
#   and have worked with PyTorch, TensorFlow, scikit-image and Dask. I am used to work with git and continues integration
#   to ensure the quality of the solutions I provide.
  
#   I am experienced in working with different imaging modalities from light to electron microscopy and handling all 
#   types of imaging data, from small 2D images to large 5D datasets.
  
#   I am passionate about making state of the art technology available to people without a computer science 
#   background.
  

# content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Image Processing & Analysis Project Template
#         link: https://fmi-faim.github.io/ipa-project-template/
#         additional_links:
#           - title:  fmi-faim/ipa-project-template
#             icon: fab fa-github
#             url: https://github.com/fmi-faim/ipa-project-template
#         quote: >
#           A template to get your image processing and analysis project started.
#         description: | # this will include new lines to allow paragraphs
#           Image Processing and Analysis (IPA), transforming raw image data into quantitative measurements, is an 
#           important part of life sciences. This template simplifies the initiation of new IPA projects and streamlines
#           the reorganization of existing ones, contributing to research that is more Findable, Accessible, 
#           Interoperable, and Reusable (FAIR) promoting efficiency, reproducibility, and reliability in life 
#           sciences research.
#       - layout: top-middle
#         title: Napari PSF Analysis
#         link: https://github.com/fmi-faim/napari-psf-analysis
#         additional_links:
#           - title:  fmi-faim/napari-psf-analysis
#             icon: fab fa-github
#             url: https://github.com/fmi-faim/napari-psf-analysis
#         quote: >
#           Inspect the point spread function (PSF) of your microscope.
#         description: | # this will include new lines to allow paragraphs
#           This plugin is used to analyze the point spread function of microscopes. It provides a simple and easy to use
#           interface, which allows us to quickly assess the state of our microscopes. The quality measurements are are collected
#           and stored in a database, which allows us to track the performance of our microscopes over time.

#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: Machine Learning Expert
#         link: https://www.fmi.ch/platforms/platform.html?plt=110
#         link_text: Friedrich Miescher Institute for Biomedical Research
#         sub_title: Facility for Advanced Imaging and Microscopy
#         caption: July 2021 - Present
#         description: | # this will include new lines to allow paragraphs
#           In my role as Machine Learning Expert in the Facility for Advanced Imaging and Microscopy I work together with
#           our research groups to develop and implement state of the art image processing and analysis pipelines. The projects I 
#           work on are a diverse mix, ranging from small scale image analysis tasks to processing of terabyte sized imaging
#           datasets. I also educate our users in the best practices of FAIR image processing and analysis.
#       - layout: left
#         title: Doctoral Researcher
#         caption: 2017 - 2021
#         sub_title: Center for Systems Biology Dresden
#         description: | # this will include new lines to allow paragraphs
#           Next to researching novel approaches for image restoration, it was always a passion of mine to make our 
#           research outputs accessible to the wider non-computer scientist community. Making state of the art technology 
#           available to researchers without a computer science background is a challenge I enjoy.
#       - layout: left
#         title: Student Assistant
#         sub_title: Junior Programmer
#         caption: 2014 - 2017
#         description: | # this will include new lines to allow paragraphs
#           During my bachelor and master studies I worked as student assistant at the Chair for Bioinformatics and 
#           Information Mining. During this time I developed KNIME workflows and plugins for image processing and
#           analysis. As part of my work I also contributed to ImageJ and Fiji, two widely used image processing tools in
#           the life sciences.

#   # - title: Education # Title for the section
#   #   layout: list # Type of content section (list/text)
#   #   content:
#   #     - layout: left
#   #       title: Technische Universität Dresden
#   #       caption: 2017 - 2021
#   #       sub_title: 
#   #       description: | # this will include new lines to allow paragraphs
#   #         I developed novel machine learning methods for image restoration in the field of biomedical image analysis.
#   #         As a member of the IMPRS-CellDevoSys school, hosted at the Max Planck Institute of Molecular Cell Biology and 
#   #         Genetics (MPI-CBG) in collaboration with the Technische Universität Dresden (TUD), I was part of a vibrant 
#   #         and interdisciplinary research community. I worked together with researchers from biology, chemistry, 
#   #         physics and computer science.  

#   # - title: Teaching & Extracurricular Activities
#   #   layout: text
#   #   content: | # this will include new lines to allow paragraphs
#   #     Alongside my daily work I am involved in different teaching activities:
#   #     * [ZIDAS 2024](https://2024.zidas.org/): Co-organizer of the 2024 edition of the ZIDAS summer school.
#   #     * [ZIDAS 2023](https://2023.zidas.org/): Co-organizer of the 2023 edition of the ZIDAS summer school.
#   #     * [ZIDAS 2022](https://2022.zidas.org/): Co-organizer of the 2022 edition of the ZIDAS summer school.
#   #     * 2019 Dresden Senioren Akademie: Wie können lernende Algorithmen unsichtbare Inhalte in mikroskopischen Bildern sichtbar machen?
#   #     * 2019 Output DD: Computer Vision Meets Biology - Basic Research Requires Open Source Solutions

# # Footer
# footer_show_references: true
# # references_title: References on request (Override references text)

# sass:
#   sass_dir: _sass
#   style: compressed

# plugins:
#  - jekyll-seo-tag



 # _config.yml

# Site settings
title: Aman Kukde's Portfolio
email: kukdeaman.dhanraj.bme19@iitbhu.ac.in
description: >
  Welcome to the portfolio of Aman Kukde, an Integrated Dual Degree (B.Tech. + M.Tech) student in Biomedical Engineering from IIT (BHU), Varanasi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Personal Information
name: Aman Kukde
linkedin: "https://www.linkedin.com/in/your-linkedin-profile"
github: "https://github.com/AmanKukde"
phone: "+91 8329538281"
content:
  # Education
  - title: Education
    layout: list
    content :
      - institute: Indian Institute of Technology (BHU), Varanasi, India
        caption: 2019 – 2024
        sub_title: Integrated Dual Degree (B.Tech. + M.Tech) in Biomedical Engineering
        gpa: 8.96
        description: | # this will include new lines to allow paragraphs
          I developed novel machine learning methods for image restoration in th

  # Experience
  title: Experience:
    layout: list
    content:
      -layout: left
      - title: Master’s Thesis Internship
        sub_title: Human Technopole
        location: Milan, Italy
        caption: Jan 2024 – July 2024
        supervisor: Dr. Florian Jug
        description:
          - Worked on Master’s Thesis project on Image Reconstruction using sequential 2D Fourier representation of images.
          - Extended methodology with SSMs like Mamba, explored novel token encoding, and hybridized architectures.
          - Achieved faster inference times and reduced GPU memory requirements than existing Attention based models

      - title: Research Internship
        sub_title: Institut Pasteur
        location: Paris, France
        caption: May 2022 – July 2022
        supervisor: Dr. Pauline Spéder
        description:
          - Quantified Cortical tension in brain cells of fruit flies using microscopy and computational techniques.
          - Developed end-to-end Jupyter notebook to segment cells and process the 4D stacks to track ablated cell membrane.
          - Research paper is in the works and to be submitted imminently

      - title: Biomedical Data Science Internship
        sub_title: LifeSignals India Pvt. Ltd.
        location: Bangalore, India
        caption: Jan 2022 – Feb 2023
        description:
          - Predicted Blood Pressure from real-world ECG and PPG data acquired from the company’s wearable product.
          - Clustered patients together based on demographics, disorders, medication and signal data features for modelling BP.
          - Developed end-to-end pipeline for data-scraping, preprocessing, model training and generation of reports.

  # Projects
  projects:
    - title: Automated Licence Plate Recognition System
      technologies: [OpenCV, PyTorch, CNN, YOLOv6]
      description:
        - Built a complete system to extract registration numbers of vehicles from unconstrained real-world images.
        - Applied YOLOv6 for plate detection, contours-based character segmentation, and CNNs for classification.
        - Handled noise removal, histogram equalization, and perspective transform to resolve image irregularities.

    - title: Semantic Segmentation of Brain Tumours in MRI Images
      technologies: [PyTorch, CNNs, 3D U-Net]
      description:
        - Implemented various versions of the UNet architecture for brain tumor segmentation in MRI scans (BraTS 2020).
        - Explored modern CV techniques and ‘Attention Mechanism’ to improve segmentation accuracy.
        - Refined UNet model achieving 60% fewer parameters than the original with superior performance & reduced loss.

    - title: Cardiac Disease Detection using ECG
      technologies: [Signal Processing, Keras, CNNs, XAi]
      description:
        - Utilized BeautifulSoup for scraping patients’ ECG data and implemented heartbeat detection & signal de-noising techniques.
        - Constructed a 1D CNN model achieving 98% sensitivity, while also integrating GradCAM for model interpretability.

    - title: Automated German Traffic Signs Recognition
      technologies: [PyTorch, CNNs, STNs, XAi]
      description:
        - Built an image classifier using Spatial Transformer Networks (STNs) and CNNs for the GTSRB dataset.
        - Worked on Model Interpretability and Explainability (XAI) using t-SNE plots and Saliency maps.

  # Skills
  skills:
    languages: [Python, SQL, C++ (Basics), Bash, SLURM, LaTeX]
    libraries: [PyTorch, Lightning, Keras, Numpy, Pandas, Matplotlib, Seaborn, SciKitLearn, Scipy, OpenCV, HuggingFace]
    tools: [MS Office Suite, VS Code, Figma, FiJi, Jupyter, BitBucket, WandB, Tensorboard, Git, GitHub]

  # Positions of Responsibility
  positions_of_responsibility:
    - title: Associate Teaching Assistant
      sub_title: EMBO - Deep Learning for Microscopic Image Analysis (DL4MIA) Course
      location: Milan, Italy
      caption: May 2024
      description:
        - Participated in the testing of course materials and exercises to evaluate quality and effectiveness.
        - Assisted students with hands-on support through clarifying doubts and offering guidance during Project Sessions.

    - title: Teaching Assistant
      sub_title: Indian Institute of Technology (BHU), Varanasi
      location: Varanasi, India
      caption: Jul 2023 – Jan 2024
      supervisor: Prof. Dr. Neeraj Sharma
      description:
        - Conducted practical sessions and supervised students in Signal and Image Processing course (BM502).
        - Proctored exams and graded assignments and provided feedback on student work.
        - Clarified concepts, addressed doubts, and provided support to students.

    - title: Head of Content Team
      sub_title: Health and Hygiene Club, IIT (BHU), Varanasi
      location: Varanasi, India
      caption: Jul 2021 – May 2021
      description:
        - Led the creative aspects of the club with a team of 5 members and 30k+ total social media impressions.
        - Organized impactful campaigns related to Malnutrition, Sanitation, Menstruation & Women’s health.
