# Site
favicon: images/favicon.ico

# Personal info
name: Aman Kukde
title: Biomedical Data Scientist
email: kukdeaman.dhanraj.bme19@iitbhu.ac.in
#website: https://tibuch.ch

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  AmanKukde
linkedin_username: amankukde
# orcid_username: 0000-0001-6953-8915

# Additional icon links
additional_links:
- title: Jug Lab, Human Technopole, Milan, Italy 
  icon: fas fa-globe
  url: https://humantechnopole.it/en/research-groups/jug-group/

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Aman Kukde and I'm a Biomedical Data Scientist. I graduated from the Indian Institute of Technology (BHU), Varanasi, with a GPA of 8.96. 
  My academic journey has been enriched by internships at prestigious institutions, under 'Industry Leaders' of their respective fields. <br> These experiences have equipped me with both wet lab and computational skills relevant to the field of Biomedical Engineering. <br>
  My research interests include Machine Learning, Computer Vision, and Biomedical Data Science. <br> I am currently seeking PhD position in the field of 'Applications of Deep Learning for Biomedical Imaging'
  

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology (BHU), Varanasi
        caption: 2019 - 2024
        sub_title: Integrated Dual Degree (B.Tech + M.Tech), Biomedical Engineering
        description: | # this will include new lines to allow paragraphs
          I am currently enrolled in the integrated dual degree program at the Indian Institute of Technology (BHU), 
          Varanasi.<br>The program combines a bachelor and master degree in biomedical engineering.<br>During my studies I 
          focused on Machine Learning and Artificial Intelligence in the context of biomedical imaging.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Master’s Thesis Internship
        link: https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://humantechnopole.it/en/research-groups/jug-group/&ved=2ahUKEwj_isu2opiGAxU7h_0HHfVfBDQQFnoECA0QAQ&usg=AOvVaw2lnOkZh76YH7S9EPexzaTJ
        link_text: Supervisor - Dr. Florian Jug
        sub_title: Human Technopole, Milan, Italy
        caption: Jan 2024 - July 2024
        description: | # this will include new lines to allow paragraphs
          Worked on Master’s Thesis project on Image Reconstruction using sequential 2D Fourier representation of images. 
          <br>Extended methodology with SSMs like Mamba, explored novel token encoding, and hybridized architectures.
          <br>Achieved faster inference times and reduced GPU memory requirements than existing Attention based model
      - layout: left
        title: Research Intern
        link: http://www.speder-lab.com
        link_text: Supervisor - Dr. Pauline Spéder
        sub_title: Institut Pasteur, Paris, France
        caption: May 2022 - July 2022
        description: | # this will include new lines to allow paragraphs
          Quantified Cortical tension in brain cells of fruit flies using microscopy and computational techniques.
          <br>Developed end-to-end Jupyter notebook to segment cells and process  the 4D stacks to track ablated cell membrane
          <br>Research paper is in the works and to be submitted imminently**
      - layout: left
        title: Biomedical Data Science Intern
        link: http://www.lifesignals.com
        link_text: Website
        sub_title: LifeSignals India Pvt. Ltd., Bangalore, India
        caption: Jan 2022 - Feb 2023
        description: | # this will include new lines to allow paragraphs
          Predicted Blood Pressure from real-world ECG and PPG data acquired from the company's wearable product.
          <br>Clustered patients together based on demographics, disorders, medication and signal data features for modelling BP.
          <br>Developed end-to-end pipeline for data-scraping, preprocessing, model training and generation of reports.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Automated License Plate Recognition
        sub_title: ~ OpenCV,PyTorch,CNN,YOLOv6 ~
        description: # this will include new lines to allow paragraphs
          • Built a complete system to extract registration numbers of vehicles from unconstrained real-world images. <br>
          • Applied YOLOv6 for plate detection, contours-based character segmentation, and CNNs for classification. <br>
          • Handled noise removal, histogram equalization, and perspective transform to resolve image irregularities. <br>

      - layout: left
        title: Semantic Segmentation of Brain Tumours in MRI Images
        sub_title: ~ PyTorch, CNNs, 3D U-Net ~
        description: | # this will include new lines to allow paragraphs
          • Implemented various versions of the UNet architecture for brain tumor segmentation in MRI scans (BraTS 2020). <br>
          • Explored modern CV techniques and ’Attention Mechanism’ to improve segmentation accuracy. <br>
          • Refined UNet model achieving 60% fewer parameters than the original with superior performance & reduced loss. <br>

      - layout: left
        title: Cardiac Disease Detection using ECG
        sub_title: ~ Signal Processing, Keras, CNNs, XAi ~
        description: | # this will include new lines to allow paragraphs
          • Utilized BeautifulSoup for scraping patients’ ECG data and implemented heartbeat detection & signal de-noising techniques in Python. <br>
          • Constructed a 1D CNN model achieving 98% sensitivity, while also integrating GradCAM for model interpretability. <br>

      - layout: left
        title: Automated German Traffic Signs Recognition
        sub_title: ~ PyTorch, CNNs, STNs, XAi ~
        description: | # this will include new lines to allow paragraphs
          • Built an image classifier using Spatial Transformer Networks (STNs) and CNNs for the GTSRB dataset. <br>
          • Worked on Model Interpretability and Explainability (XAI) using t-SNE plots and Saliency maps, etc. <br>



  # - title: Selected Publications
  #   layout: list
  #   content:
  #     - layout: left
  #       title: N2V2
  #       link: https://arxiv.org/abs/2211.08512
  #       caption: 2022
  #       description: |
  #         ## N2V2 - Fixing Noise2Void Checkerboard Artifacts with Modified Sampling Strategies and a Tweaked Network Architecture
  #         __E Höck\*, TO Buchholz\*, A Brachmann, F Jug, A Freytag__
          
  #         Noise2Void 2 (N2V2) fixes the checkerboard artifacts that are present in some Noise2Void (N2V) denoised images.

  #     - layout: left
  #       title: cryoCARE
  #       link: https://arxiv.org/abs/1810.05420
  #       caption: 2019
  #       description: |
  #         ## cryoCARE - Content-Aware Image Restoration for Cryo-Transmission Electron Microscopy Data
  #         __TO Buchholz, M Jordan, G Pigino, F Jug__
          
  #         Even highest quality cryo-EM data is inherently noisy and suffers from low contrast. With cryoCARE we present 
  #         a deep learning-based approach to denoise and improve contrast in cryo-EM data.

  #     - layout: left
  #       title: Noise2Void
  #       link: https://arxiv.org/abs/1811.10980
  #       caption: 2019
  #       description: |
  #         ## Noise2Void - Learning Denoising from Single Noisy Images
  #         __A Krull\*, TO Buchholz\*, F Jug__
          
  #         Noise2Void is a self-supervised image denoising method based on deep learning. It does not require clean 
  #         ground truth data for training, instead it can be trained on single noisy images only.
  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
