# Site
favicon: images/favicon.ico

# Personal info
name: Aman Kukde
title: Biomedical Data Scientist
email: kukdeaman.dhanraj.bme19@iitbhu.ac.in
#website: https://amankukde.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: AmanKukde
linkedin_username: amankukde

# Additional icon links
additional_links:
- title: Jug Lab, Human Technopole, Milan, Italy 
  icon: fas fa-globe
  url: https://humantechnopole.it/en/research-groups/jug-group/

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  ⬩ Biomedical Data Scientist with expertise in AI, Computer Vision, and Biomedical Imaging.<br>
  ⬩ Experience in deep learning applications for medical image analysis, signal processing, and computational biology.<br>
  ⬩ Currently pursuing a PhD at Human Technopole, Milan, focusing on AI-driven biomedical imaging advancements.<br>

content:

  - title: Education
    layout: list
    content:
      - layout: left
        title: Indian Institute of Technology (BHU), Varanasi
        caption: 2019 - 2024
        sub_title: (B.Tech + M.Tech), Biomedical Engineering (CGPA: 8.86/10)
        description: |
          - Graduated with a CGPA of 8.86/10, specializing in biomedical imaging and AI applications.<br>
          - Coursework included medical imaging, AI, regenerative medicine, and signal processing.<br>

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Associate - II (United Airlines Project)
        sub_title: Indus Insights & Analytics, India
        caption: July 2024 – Feb 2025
        description: |
          • Led customer segmentation and predictive modeling, optimizing offers for ~30M users, yielding $20M in revenue.<br>
          • Developed scalable ML pipelines, reducing processing time from two weeks to **two hours (96% reduction)**.<br>

      - layout: left
        title: Master's Thesis Internship
        sub_title: Human Technopole, Milan, Italy
        caption: Jan 2024 - July 2024
        description: |
          • Winner of **Best Poster Award at HT PhD and PostDoc Symposium 2024**.<br>
          • Developed a Mamba-based AI model for image super-resolution, improving speed and reducing GPU memory usage.<br>
          • Integrated Fourier-domain encoding for enhanced biomedical image reconstruction.<br>

      - layout: left
        title: Data Scientist Intern
        sub_title: LifeSignals India Pvt. Ltd., Bangalore
        caption: Jan 2022 - Feb 2023
        description: |
          • Developed AI models for cuffless blood pressure prediction using ICU patient ECG & PPG data.<br>
          • Improved ECG/PPG signal quality by **35%** using advanced filtering and denoising techniques.<br>
          • Reduced model size by **60%** via knowledge distillation while maintaining **95% accuracy**.<br>

      - layout: left
        title: Research Intern
        sub_title: Institut Pasteur, Paris, France
        caption: May 2022 - July 2022
        description: |
          • Studied neural stem cell behavior using advanced imaging & laser ablation techniques.<br>
          • Semi-Automated membrane landmark detection and quantified mechanical tension in brain tissue.<br>

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Semantic Segmentation of Brain Tumours
        sub_title: ~ PyTorch, U-Net, Attention U-Net ~
        description: |
          • Improved UNet-based tumor segmentation models, reducing loss by **50%** and model size by **45% (~3M params)**.<br>
          • Integrated attention mechanisms to enhance feature extraction in MRI images.<br>

      - layout: left
        title: Cardiac Disease Detection using ECG
        sub_title: ~ Signal Processing, CNNs, XAi ~
        description: |
          • Developed ECG classification model achieving **98% sensitivity, 96% specificity, and 97% accuracy**.<br>
          • Applied advanced filtering & heartbeat detection for signal preprocessing.<br>

  - title: Publications
    layout: list
    content:
      - layout: left
        title: Adhesion-Controlled Mechanics of the Glial Niche
        sub_title: (*Submitted to Cell, Nov 2024)
        description: |
          • Investigated the role of adhesion molecules in neural stem cell regulation using computational imaging techniques.<br>

  - title: Additional Activities
    layout: list
    content:
      - layout: left
        title: International Hackathons
        sub_title: Ai4Life Hackathon | Germany, Mar ’24 ; Spain, June ’24
        description: |
          • Enhanced BioImageIO model uploader wrapper, resolving deployment issues & improving efficiency.<br>

      - layout: left
        title: Teaching & Volunteering
        sub_title: IIT BHU & EMBO DL4MIA Course
        description: |
          • Assisted in deep learning courses and image processing workshops at IIT BHU and Human Technopole.<br>

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
