# Site
favicon: images/favicon.ico

# Personal info
name: Tim-Oliver Buchholz
title: Machine Learning Expert for Image Analysis
email: contact-tibuch@protonmail.ch
#website: https://tibuch.ch

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  tibuch
linkedin_username: tibuch
orcid_username: 0000-0001-6953-8915

# Additional icon links
additional_links:
- title: Current Workplace
  icon: fas fa-globe
  url: https://www.fmi.ch/platforms/platform.html?plt=110

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Tim-Oliver and I am a research software engineer. I work on biomedical image processing and analysis 
  pipelines. Next to my work as software engineer I educate researchers in the best practices of FAIR image processing 
  and analysis. I have worked with a number of different research groups and have experience in a wide range of image 
  processing and analysis tasks.
  
  In my day-to-day work I use a variety of different programming languages and tools. I am experienced in Python and Java,
  and have worked with PyTorch, TensorFlow, scikit-image and Dask. I am used to work with git and continues integration
  to ensure the quality of the solutions I provide.
  
  I am experienced in working with different imaging modalities from light to electron microscopy and handling all 
  types of imaging data, from small 2D images to large 5D datasets.
  
  I am passionate about making state of the art technology available to people without a computer science 
  background.
  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Image Processing & Analysis Project Template
        link: https://fmi-faim.github.io/ipa-project-template/
        additional_links:
          - title:  fmi-faim/ipa-project-template
            icon: fab fa-github
            url: https://github.com/fmi-faim/ipa-project-template
        quote: >
          A template to get your image processing and analysis project started.
        description: | # this will include new lines to allow paragraphs
          Image Processing and Analysis (IPA), transforming raw image data into quantitative measurements, is an 
          important part of life sciences. This template simplifies the initiation of new IPA projects and streamlines
          the reorganization of existing ones, contributing to research that is more Findable, Accessible, 
          Interoperable, and Reusable (FAIR) promoting efficiency, reproducibility, and reliability in life 
          sciences research.
      - layout: top-middle
        title: Napari PSF Analysis
        link: https://github.com/fmi-faim/napari-psf-analysis
        additional_links:
          - title:  fmi-faim/napari-psf-analysis
            icon: fab fa-github
            url: https://github.com/fmi-faim/napari-psf-analysis
        quote: >
          Inspect the point spread function (PSF) of your microscope.
        description: | # this will include new lines to allow paragraphs
          This plugin is used to analyze the point spread function of microscopes. It provides a simple and easy to use
          interface, which allows us to quickly assess the state of our microscopes. The quality measurements are are collected
          and stored in a database, which allows us to track the performance of our microscopes over time.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Master’s Thesis Internship
        link: https://www.fmi.ch/platforms/platform.html?plt=110
        link_text: Human Technopole, Milan, Italy
        sub_title: Facility for Advanced Imaging and Microscopy
        caption: Jan 2024 - July 2024
        description: | # this will include new lines to allow paragraphs
          Worked on Master’s Thesis project on Image Reconstruction using sequential 2D Fourier representation of images. 
          Extended methodology with SSMs like Mamba, explored novel token encoding, and hybridized architectures.
          Achieved faster inference times and reduced GPU memory requirements than existing Attention based model
      - layout: left
        title: Research Intern
        caption: May 2022 - July 2022
        sub_title: Institut Pasteur, Paris, France
        description: | # this will include new lines to allow paragraphs
          Quantified Cortical tension in brain cells of fruit flies using microscopy and computational techniques.
          Developed end-to-end Jupyter notebook to segment cells and process  the 4D stacks to track ablated cell membrane
          Research paper is in the works and to be submitted imminently**
      - layout: left
        title: Biomedical Data Science Intern
        sub_title: LifeSignals India Pvt. Ltd., Bangalore, India
        caption: Jan 2022 - Feb 2023
        description: | # this will include new lines to allow paragraphs
        Predicted Blood Pressure from real-world ECG and PPG data acquired from the company's wearable product.
        Clustered patients together based on demographics, disorders, medication and signal data features for modelling BP.
        Developed end-to-end pipeline for data-scraping, preprocessing, model training and generation of reports.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology (BHU), Varanasi
        caption: 2019 - 2024
        sub_title: Integrated Dual Degree (B.Tech + M.Tech), Biomedical Engineering
        description: | # this will include new lines to allow paragraphs
          I am currently enrolled in the integrated dual degree program at the Indian Institute of Technology (BHU), 
          Varanasi. The program combines a bachelor and master degree in biomedical engineering. During my studies I 
          focused on Machine Learning and Artificial Intelligence in the context of biomedical imaging.

  # - title: Teaching & Extracurricular Activities
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my daily work I am involved in different teaching activities:
  #     * [ZIDAS 2024](https://2024.zidas.org/): Co-organizer of the 2024 edition of the ZIDAS summer school.
  #     * [ZIDAS 2023](https://2023.zidas.org/): Co-organizer of the 2023 edition of the ZIDAS summer school.
  #     * [ZIDAS 2022](https://2022.zidas.org/): Co-organizer of the 2022 edition of the ZIDAS summer school.
  #     * 2019 Dresden Senioren Akademie: Wie können lernende Algorithmen unsichtbare Inhalte in mikroskopischen Bildern sichtbar machen?
  #     * 2019 Output DD: Computer Vision Meets Biology - Basic Research Requires Open Source Solutions

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
